source.. = src/main/java/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               headless-ui-extension-points.properties,\
               resources/plugin.xml,\
               schema/,\
               plugin.xml
