com.katalon.platform.api.extension.newToolItem=true
com.katalon.platform.api.extension.newDropdownToolItem=true
com.katalon.platform.api.extension.pluginPreferencePage=true
com.katalon.platform.api.extension.testCaseIntegrationViewDescription=true
com.katalon.platform.api.extension.testSuiteIntegrationViewDescription=true
com.katalon.platform.api.extension.reportIntegrationViewDescription=true
com.katalon.platform.api.extension.testSuiteUIViewDescription=true
com.katalon.platform.api.extension.testSuiteCollectionUIViewDescription=true
